spring:
  profiles:
    active: dev
---
server:
  port: 7001

spring:
  profiles: dev #开发环境

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka7002.com:7002/eureka
---
server:
  port: 7001

spring:
  profiles: prod #生产环境

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka7002.com:7002/eureka