spring:
  profiles:
    active: dev
---
server:
  port: 8888
spring:
  profiles: dev
  application:
    name: springcloud-zuul-8888
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true
zuul:
  routes:
    provider-user:
      path: /user/**
      serviceId: user-customer-provinder
      stripPrefix: false  #代理转发时去掉前缀，false:代理转发时不去掉前缀 例如:为true时请求 /product/get/1，代理转发到/get/1
    provider-customer:
      path: /customer/**
      serviceId: user-customer-provinder
      stripPrefix: false  #代理转发时去掉前缀，false:代理转发时不去掉前缀 例如:为true时请求 /product/get/1，代理转发到/get/1
---
server:
  port: 8888
spring:
  profiles: test
  application:
    name: springcloud-zuul-8888
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true
zuul:
  routes:
    provider-user:
      path: /user/**
      serviceId: user-customer-provinder
      stripPrefix: false  #代理转发时去掉前缀，false:代理转发时不去掉前缀 例如:为true时请求 /product/get/1，代理转发到/get/1
    provider-customer:
      path: /customer/**
      serviceId: user-customer-provinder
      stripPrefix: false  #代理转发时去掉前缀，false:代理转发时不去掉前缀 例如:为true时请求 /product/get/1，代理转发到/get/1
---
server:
  port: 8888
spring:
  profiles: prod
  application:
    name: springcloud-zuul-8888
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true
zuul:
  routes:
    provider-user:
      path: /user/**
      serviceId: user-customer-provinder
      stripPrefix: false  #代理转发时去掉前缀，false:代理转发时不去掉前缀 例如:为true时请求 /product/get/1，代理转发到/get/1
    provider-customer:
      path: /customer/**
      serviceId: user-customer-provinder
      stripPrefix: false  #代理转发时去掉前缀，false:代理转发时不去掉前缀 例如:为true时请求 /product/get/1，代理转发到/get/1